### ISSUE TITLE
Typo in License section

### ISSUE THREAD

**Issue by Screwland** [syohex/emacs-mruby-test#1]
`This software is released unser the GPLv3.`->`This software is released under the GPLv3.`

In addition,  mruby-core.c and mruby.el are licensed under the GPLv3 or (at your option) any later version.

So I recommend like this:
`This software is released under the GPLv3+.`
or
`This software is released under the GPLv3 or (at your option) any later version.`

And I hope that you add COPYING FILE to top directory.

**Comment by syohex** [comment]
Thanks for reporting. I have fixed typo and add `COPYING` file.

**Comment by Screwland** [comment]
Thank you too!
